"""Agregar relacion carrito a  usuario

Revision ID: 455652cbe5f8
Revises: f9ce786206c5
Create Date: 2026-05-03 22:38:35.444547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455652cbe5f8'
down_revision: Union[str, Sequence[str], None] = 'f9ce786206c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
