"""agregar tablas de carrito y pedidos

Revision ID: b79b029da9cc
Revises: ebe94ba34d20
Create Date: 2026-04-28 20:39:15.465085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79b029da9cc'
down_revision: Union[str, Sequence[str], None] = 'ebe94ba34d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
